name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the CUDA Docker image
      run: docker build . --file CUDA/Dockerfile --tag biniou-cuda:$(date +%s)
