name: Docker Image CI

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the CPU Docker image
      run: docker build . --file Dockerfile --tag biniou-cpu:$(date +%s)
