name: Test of Windows installer

on:
  push:
    branches: [ "main" ]
    paths:
      - ./install_win.cmd
      - ./requirements.txt
      - ./update_win.cmd
      - ./update_win_cuda.cmd
  pull_request:
    branches: [ "main" ]
    paths:
      - ./install_win.cmd
      - ./requirements.txt
      - ./update_win.cmd
      - ./update_win_cuda.cmd
jobs:

  install:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - name: Windows installer test
      run: powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"https://raw.githubusercontent.com/Woolverine94/biniou/main/install_win.cmd\", \"install_win.cmd\")"
      run: .\install_win.cmd

    steps:
    - uses: actions/checkout@v4
    - name: Windows updater test
      run: biniou\update_win_cuda.cmd

    steps:
    - uses: actions/checkout@v4
    - name: Windows CUDA updater test
      run: biniou\update_win_cuda.cmd
